### ISSUE TITLE
something wrong when converting Aircraft

### ISSUE THREAD

**Issue by macn3388** [tau-yihouxiang/WS_DAN#6]
$ python convert_data.py --dataset_name=Aircraft --dataset_dir=./Aircraft/Data
Traceback (most recent call last):
  File "convert_data.py", line 76, in <module>
    tf.app.run()
  File "/mnt/disk0/home/mahailong/anaconda3/envs/CenterNet/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "convert_data.py", line 65, in main
    convert_aircraft.run(FLAGS.dataset_dir)
  File "/mnt/disk0/home/mahailong/WS_DAN/datasets/convert_aircraft.py", line 196, in run
    train_dataset, test_dataset = generate_datasets(dataset_dir)
  File "/mnt/disk0/home/mahailong/WS_DAN/datasets/convert_aircraft.py", line 155, in generate_datasets
    train_info = np.loadtxt(os.path.join(data_root, 'fgvc-aircraft-2013b/data', 'images_variant_trainval.txt'), str)
  File "/mnt/disk0/home/mahailong/anaconda3/envs/CenterNet/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1141, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/mnt/disk0/home/mahailong/anaconda3/envs/CenterNet/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1065, in read_data
    % line_num)
ValueError: Wrong number of columns at line 1235

**Comment by ghost** [comment]
same problem as you,do you solve it?

**Comment by breadbread1984** [comment]
replace spaces in aircraft name with '-' or some other none space character
